### ISSUE TITLE
ipq4019

### ISSUE THREAD

**Issue by zeilsteen2** [adron-s/mtik_initrd_hacks#2]
Thanks for the tool!

Tried it on an IPQ4019 (wAP60g) but it is not working with the pre-build arm.
Also build a new one because I thought maybe it was the other soc. But that is also not working on the ipq4019.

Should the pre-build arm release work on the ipq4019?

Thanks

**Comment by prisonmike168** [comment]
Hello, I am experiencing the exact same issue, image seems to be loaded via bootp method, but telnet port 22111 remains to be unreachable

Tested with firmware 7.1rc4, 7.2rc1 and 7.2rc4

**Comment by adron-s** [comment]
Hello friends. I made a number of fixes today to work on ipq40xx devices. In particular, I needed to investigate the work of hAP AC2, but due to the too small amount of its flash memory, I could not use my initrd hack. To solve this problem, I added support for launching a busybox from a USB flash drive. And it works great for hAP AC2. Just upload OWL files to disk1(USB flash drive) and tftpboot.

Tested on RouterOS 7.2.3. Ready to use arm kernel: https://github.com/adron-s/mtik_initrd_hacks/blob/master/ready-kernels/kernel-new-7.2.3-arm.elf?raw=true

**Comment by dchard** [comment]
Trying on hAP AC3 LTE kit with kernel 7.2.3, no luck there. Unit is on ROS 7.2.3, the OWL files are uploaded to the flash (it barely fits), the unit boots with TFTP downloading the hacked kernel, yet there is no telnet access available.

![image](https://user-images.githubusercontent.com/8152156/190910748-c4e18bd0-964c-4ad3-981a-d0aa13fe1d7a.png)

MOD: I tried to revert to 7.2RC1, no luck there as well.

**Comment by adron-s** [comment]
Hello @dchard.
Try to move the OWL dir to the disk1(extX flash drive). My [last commit](https://github.com/adron-s/mtik_initrd_hacks/commit/a6f257a42ef6f89df14c0c81b28cd7b280639c14) just changes init to find OWL dir on disk1.

**Comment by dchard** [comment]
Hi @adron-s 

I tried that too, no luck. The pendrive is formatted to fat32, ROS recognizes it, so I assume that is not a problem.

MOD: I see in the commit message that the USB drive needs to be ext3, I formatted a drive to ext3, put the files in the root like this:

/pub/OWL/bin/busybox
/pub/OWL/OWL.sh

Still does not work.

Tried like:

/OWL/bin/busybox
/OWL/OWL.sh

Still does not work.

As I only see no bootloader activity after your kernel gets netbooted, I would assume your kernel works, but the telnetd is not started. Or you expected a specific IP or a specific network setup? I have 192.168.1.10/24 IP set on ether1, not part of a bridge.

**Comment by adron-s** [comment]
> The pendrive is formatted to fat32, ROS recognizes it, so I assume that is not a problem.

I think this is the problem. Format the flash drive in the RouterOS itself in the ext3/4 file system.

**Comment by dchard** [comment]
> > The pendrive is formatted to fat32, ROS recognizes it, so I assume that is not a problem.
> 
> I think this is the problem. Format the flash drive in the RouterOS itself in the ext3/4 file system.

Disk is formatted to ext3 under ROS, files copied:

![image](https://user-images.githubusercontent.com/8152156/191026890-412d603c-7422-4d09-8695-ce2c1267df3d.png)

Still does not work.

**Comment by adron-s** [comment]
> > > The pendrive is formatted to fat32, ROS recognizes it, so I assume that is not a problem.
> > 
> > 
> > I think this is the problem. Format the flash drive in the RouterOS itself in the ext3/4 file system.
> 
> Disk is formatted to ext3 under ROS, files copied:
> 
> ![image](https://user-images.githubusercontent.com/8152156/191026890-412d603c-7422-4d09-8695-ce2c1267df3d.png)
> 
> Still does not work.

Just checked on my test hap-ac3. I reinstall RouterOS through NetInstall and just uploaded files via FTP (pub folder). The flash drive has not been used. Everything worked great at the first time!

![изображение](https://user-images.githubusercontent.com/17401751/191028271-16c790bd-cfc9-4e39-95d7-189c9bb7ff4b.png)

**Comment by dchard** [comment]
What needed to be done is rename the disk from disk5 to disk1, then reupload the files so it looks like this:

![image](https://user-images.githubusercontent.com/8152156/191041787-5b09607b-be74-4d73-bb94-328076140f7b.png)

Note that during upload, that "bin/basename" part was "bin/busybox", and after the first successful boot it now looks like this, and root shell works.

**Comment by dchard** [comment]
@adron-s for OWRT development this is quite a useful tool. What would be lovely is if you can produce a hacked kernel for a more recent version 6 one, like 6.49.6 for example. There are never units which are not working with the currently available v6 kernels, but hacking on V7 is still quite problematic.

**Comment by adron-s** [comment]
> @adron-s for OWRT development this is quite a useful tool. What would be lovely is if you can produce a hacked kernel for a more recent version 6 one, like 6.49.6 for example. There are never units which are not working with the currently available v6 kernels, but hacking on V7 is still quite problematic.

It is done: https://github.com/adron-s/mtik_initrd_hacks/blob/master/ready-kernels/kernel-new-6.49.6-arm.elf
But I not tested it.

**Comment by dchard** [comment]
> > @adron-s for OWRT development this is quite a useful tool. What would be lovely is if you can produce a hacked kernel for a more recent version 6 one, like 6.49.6 for example. There are never units which are not working with the currently available v6 kernels, but hacking on V7 is still quite problematic.
> 
> It is done: https://github.com/adron-s/mtik_initrd_hacks/blob/master/ready-kernels/kernel-new-6.49.6-arm.elf But I not tested it.

No problem. Will test and report back. Thanks!

**Comment by dchard** [comment]
@adron-s if you have a bit of time, can you please provide a "ready-kernel" for 7.7-arm by any chance? Thanks!

**Comment by adron-s** [comment]
> @adron-s if you have a bit of time, can you please provide a "ready-kernel" for 7.7-arm by any chance? Thanks!

Done: https://github.com/adron-s/mtik_initrd_hacks/blob/master/ready-kernels/kernel-new-7.7-arm.elf
